In [1]:
import numpy as np
l=np.array([1,2,3,4])
print(l)

[1 2 3 4]


In [2]:
#Memory 
#Numpy takes less memory than List
#Numpy takes 4 byte size of 1 object while list takes 14 byte size of 1 object
import sys
l=range(10)
print(sys.getsizeof(1)*len(l))
array=np.arange(10)
print(array.size*array.itemsize)

280
80


In [3]:
import numpy as np
import time

size=10000000
l1=range(size)
l2=range(size)

a1=np.arange(size)
a2=np.arange(size)

start=time.time()
r=[(x+y) for x,y in zip(l1,l2)]
print('Pyhton list took',(time.time()-size)*1000)

start=time.time()
r=a1+a2
print('Numpy took',(time.time()-size)*1000)



Pyhton list took 1605444879823.7664
Numpy took 1605444879982.9778


In [4]:
a1=np.array([2,4,6,8])
a2=np.array([3,6,9,12])
r=a1+a2
print(r)

[ 5 10 15 20]


In [5]:
a1=np.array([2,4,6,8])
a2=np.array([3,6,9,12])
r=a1-a2
print(r)

[-1 -2 -3 -4]


In [6]:
a1=np.array([2,4,6,8])
a2=np.array([3,6,9,12])
r=a1*a2
print(r)

[ 6 24 54 96]


In [7]:
a1=np.array([2,4,6,8])
a2=np.array([3,6,9,12])
r=a1/a2
print(r)

[0.66666667 0.66666667 0.66666667 0.66666667]
