In [1]:
import numpy as np
a=np.array([[1,2],[3,4],[5,6]])
print(a)

[[1 2]
 [3 4]
 [5 6]]


In [2]:
a.shape

(3, 2)

In [3]:
a.transpose()

array([[1, 3, 5],
       [2, 4, 6]])

In [4]:
a.max()

6

In [5]:
a.sum()

21

In [6]:
a.min()

1

In [7]:
a.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
# Check Dimension
a.ndim

2

In [9]:
np.arange(1,5)

array([1, 2, 3, 4])

In [10]:
np.arange(2,4)

array([2, 3])

In [11]:
a.ravel()

array([1, 2, 3, 4, 5, 6])

In [12]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [13]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [14]:
np.square(a)

array([[ 1,  4],
       [ 9, 16],
       [25, 36]])

In [15]:
np.sqrt(a)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ],
       [2.23606798, 2.44948974]])

In [16]:
a=np.array([[2,4],[6,8],[10,12]])
b=np.array([[3,6],[9,12],[15,18]])
a+b

array([[ 5, 10],
       [15, 20],
       [25, 30]])

In [17]:
a-b

array([[-1, -2],
       [-3, -4],
       [-5, -6]])

In [18]:
a*b

array([[  6,  24],
       [ 54,  96],
       [150, 216]])

In [19]:
a/b

array([[0.66666667, 0.66666667],
       [0.66666667, 0.66666667],
       [0.66666667, 0.66666667]])