In [1]:
import numpy as np
a1=np.arange(1,10).reshape(3,3)
print(a1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [2]:
a1[2,2]

9

In [3]:
a1[0:3,1]

array([2, 5, 8])

In [4]:
a1[-1]

array([7, 8, 9])

In [5]:
a1[-1,1:3]

array([8, 9])

In [6]:
a1[1:3,1]

array([5, 8])

In [7]:
a1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
a1[:,1:3]

array([[2, 3],
       [5, 6],
       [8, 9]])

In [9]:
a1[0:2,:2]

array([[1, 2],
       [4, 5]])

In [10]:
a2=np.arange(6).reshape(2,3)
a2

array([[0, 1, 2],
       [3, 4, 5]])

In [11]:
a3=np.arange(6,12).reshape(2,3)
a3

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [12]:
np.vstack((a2,a3))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [13]:
np.hstack((a2,a3))

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

In [14]:
b=np.arange(10).reshape(2,5)
b

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [15]:
result=np.hsplit(b,5)
result

[array([[0],
        [5]]),
 array([[1],
        [6]]),
 array([[2],
        [7]]),
 array([[3],
        [8]]),
 array([[4],
        [9]])]

In [16]:
result[1]

array([[1],
       [6]])

In [17]:
a=np.arange(1,13).reshape(3,4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [18]:
b=a>4
b

array([[False, False, False, False],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [19]:
a[b]

array([ 5,  6,  7,  8,  9, 10, 11, 12])

In [21]:
a[b]=-2
a

array([[ 1,  2,  3,  4],
       [-2, -2, -2, -2],
       [-2, -2, -2, -2]])

In [31]:
a=np.arange(1,16).reshape(5,3)
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [32]:
for row in a:
    print(row)

[1 2 3]
[4 5 6]
[7 8 9]
[10 11 12]
[13 14 15]


In [33]:
for cell in a.flatten():
    print(cell)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15


In [34]:
for c in np.nditer(a,order='F'):
    print(c)

1
4
7
10
13
2
5
8
11
14
3
6
9
12
15


In [35]:
for c in np.nditer(a,order='F',flags=['external_loop']):
    print(c)

[ 1  4  7 10 13]
[ 2  5  8 11 14]
[ 3  6  9 12 15]


In [36]:
for c in np.nditer(a,order='F',op_flags=['readwrite']):
    c[...]=c*c
a

array([[  1,   4,   9],
       [ 16,  25,  36],
       [ 49,  64,  81],
       [100, 121, 144],
       [169, 196, 225]])